Algoritmo "Atividade nº 3, Tabuada."

Var
   numero, multiplicador, resultado: inteiro

Inicio
   Escreva("Digite um número para ver sua tabuada: ")
   Leia(numero)

   Escreval
   Escreval("Tabuada do nº",numero,"")
   Escreva
   
   escreval
   Para multiplicador <- 1 ate 10 faca
      resultado <- numero * multiplicador
      Escreval(numero," x",multiplicador, " = ",resultado)
   FimPara

FimAlgoritmo